# ---------------------------------------------- #
#              General Configuration             #
# ---------------------------------------------- #
#              Guardians of Adelia               #
# ---------------------------------------------- #

Test: