# ---------------------------------------------- #
#             Database Configuration             #
# ---------------------------------------------- #
#                     Hikari-CP                  #
# ---------------------------------------------- #

hostname: localhost
port: 3306
database: goa
username: lixtrinn
password: asdsadfsafsabJK19034783ayu3wl12mgkj647nsdm9sf9dsfj9dsf82h32f8h2hf82f8hfhf2k2
minimumConnections: 5
maximumConnections: 20
connectionTimeout: 30000
testQuery: SELECT 1