# ---------------------------------------------- #
#             Item list Configuration            #
# ---------------------------------------------- #
#                     Items                      #
# ---------------------------------------------- #

itemSetList:
  - "slimeArmorSet"

